services:
postgres:
  image: postgres:15
    container_name: postgres
    restart: always
    environment:
      postgres_ROOT_PASSWORD: root123
      postgres_DATABASE: postgresDB
      postgres_USER: postgresuser
      postgres_PASSWORD: postgres1234
    ports:
      - "3306:3306"
    volumes:
      - postgres-data:/var/lib/postgressql/data
    networks:
      - sonar-network
 sonarqube:
    image: sonarqube:its-community
    container_name: sonarqube
    restart: always
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment: 
      postgres_URL: jdbc:postgresql://postgres:5432/postgresDB
      postgres_USER: postgresuser
      postgres_PASS: postgres1234
    networks:
      - sonar-network
volumes:
  postgres-data:
netwoversion: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: root123
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgres1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sonar-network
 sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgresDB
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgres1234
    networks:
      - sonar-network
volumes:
  postgres-data:
networks: 
  sonar-network:rks: 
  sonar-network:


